version: "3.9"

services:
  bookbase-db:
    container_name: "bookbase-db"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  bookbase-php:
    container_name: "bookbase-php"
    build:
      context: ./php
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/bookbase
    depends_on:
      - bookbase-db

  bookbase-install:
    container_name: "bookbase-install"
    build:
      context: ./php
    volumes:
      - ./www:/var/www/bookbase
    command:
      composer install --no-dev --optimize-autoloader
    depends_on:
      - bookbase-php
      - bookbase-db

  bookbase-nginx:
    container_name: "bookbase-nginx"
    image: nginx:stable-alpine
    ports:
      - "${PUBLIC_PORT}:80"
    volumes:
      - ./www:/var/www/bookbase
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bookbase-install
      - bookbase-php
      - bookbase-db
