version: "3.9"

services:
  bookbase-db:
    container_name: "bookbase-db"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./mysql:/var/lib/mysql"

  bookbase-php:
    container_name: "bookbase-php"
    build:
      context: ./php
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@bookbase-db:3306/${MYSQL_DATABASE}?serverVersion=8.0"
    ports:
      - "9000:9000"
    volumes:
      - "./www:/var/www/bookbase"
    depends_on:
      - bookbase-db

  bookbase-install:
    container_name: "bookbase-install"
    build:
      context: ./php
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@bookbase-db:3306/${MYSQL_DATABASE}?serverVersion=8.0"
    volumes:
      - "./www:/var/www/bookbase"
      - "./install/install.sh:/install.sh"
    command:
      ["/install.sh"]
    depends_on:
      - bookbase-php
      - bookbase-db

  bookbase-nginx:
    container_name: "bookbase-nginx"
    image: nginx:stable-alpine
    ports:
      - "${PUBLIC_PORT}:80"
    volumes:
      - "./www:/var/www/bookbase"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - bookbase-install
      - bookbase-php
      - bookbase-db
